### ISSUE TITLE
Could not find rgba attribute for  setting to default color

### ISSUE THREAD

**Issue by addy1997** [hu-po/aframe-urdf#1]
Hi @hu-po,

Thanks for making this component. I am trying to load Panda robot's URDF locally, but it throws these warnings(screenshot below)

`Could not find rgba attribute for  setting to default color
`

![image](https://github.com/hu-po/aframe-urdf/assets/29406906/33ad9d71-18c2-484c-bd30-f5914060bc92)

Additionally, the urdf file I am using is available [here](https://github.com/StanfordASL/PandaRobot.jl/blob/master/deps/Panda/panda.urdf) to reproduce the error.

Could you suggest something to fix this?

Thanks

**Comment by hu-po** [comment]
The urdf loader is very sensitive to materials and mesh types. For my urdf I had to [use trimesh to add material data](https://github.com/kscalelabs/meshsimplify/blob/adffc0d4bfb0740487e5032d2091326733963361/run.py#L57), perhaps that could fix your issues as well?

**Comment by addy1997** [comment]
Hi @hu-po,

How do I use the python script? Do I need to run it simultaneously while running the aframe-component?

**Comment by hu-po** [comment]
The python script will only be run once to convert the meshes that are linked in your URDF file. The script I linked is also just a reference: you will have to understand it enough to modify it for your usecase. From what I understand your problem is that the color of the meshes is wrong? Do the meshes themselves load correctly?

**Comment by addy1997** [comment]
No, the meshes don't load at all. The scene doesn't have a single mesh apart from the green plane. Also, is it possible to load the urdf file using a URL?

**Comment by hu-po** [comment]
Hmm I see in your urdf file, the meshes are referenced as:
```
        <mesh filename="package://Panda/meshes/collision/link0.obj"/>
```
in the urdf file I used the meshes are stored locally in a `meshes` folder right next to the `robot.urdf` file, which looks like this:
```
        <mesh filename="./meshes/torso_1_top_torso_1.obj" />
```
if the meshes are not loading at all it is likely they are not being found. Make sure they are right there locally.

**Comment by addy1997** [comment]
@hu-po, thanks for this. I tried changing the path but it didn't work. It appears that it is loading the meshes and the urdf file but can't find the rgba color

![image](https://github.com/hu-po/aframe-urdf/assets/29406906/acede193-b32e-41e7-b17d-1c7487e29b0b)

**Comment by hu-po** [comment]
The triangles at 3970 definitely means the meshes are loaded, agree with you on that. If you use the aframe inspector can you see the kinematic chain and the obj files? what are the material properties for the obj files on the inspector?

https://github.com/aframevr/aframe-inspector

**Comment by addy1997** [comment]
@hu-po, this is how the scene looks when I used aframe inspector

![image](https://github.com/hu-po/aframe-urdf/assets/29406906/d717d2ba-6ef3-40da-966d-6120b4212e95)

The kinematic chain isn't visible. When I click on **<a-entity panda_link0>** which is the obj file, the material properties are on the right hand side.

**Comment by hu-po** [comment]
This is what mine looks like, try and double check see if any of the properties are different?
![image](https://github.com/hu-po/aframe-urdf/assets/8493427/a93e178e-b1ec-49d9-96a8-50cabe3fed32)
![image](https://github.com/hu-po/aframe-urdf/assets/8493427/618ab362-2683-4154-b736-1bb4dfa96336)

**Comment by addy1997** [comment]
@hu-po , all properties are exactly same, except in my case, I can't see any path to the obj file (bottom of the screenshot). In your screenshot, there's a path mentioned over there *assets/urdf/tompy/./.....*

![image](https://github.com/hu-po/aframe-urdf/assets/29406906/d414fd6c-8010-41ea-9db7-5c24660a15e6)

**Comment by hu-po** [comment]
What if you manually put in the relative path of the obj file to the `index.html`?

**Comment by addy1997** [comment]
> What if you manually put in the relative path of the obj file to the `index.html`?

@hu-po, what do you mean by manually providing the path? 

Something like this?

```
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title> URDF A-Frame Example </title>
  <meta name="description" content="URDF • A-Frame">
  <script src="https://aframe.io/releases/1.5.0/aframe.min.js"></script>
  <script src="../dist/aframe-urdf.min.js"></script>
</head>

<body>
  <a-scene background="color: blue" stats
    inspector="url: https://cdn.jsdelivr.net/gh/aframevr/aframe-inspector@master/dist/aframe-inspector.min.js">

    <assets>

      <a-asset-item id="finger" src="./assets/Panda/meshes/collision/finger.obj"></a-asset-item>
      <a-asset-item id="hand" src="./assets/Panda/meshes/collision/hand.obj"></a-asset-item>
      <a-asset-item id="link0" src="./assets/Panda/meshes/collision/link0.obj"></a-asset-item>
      <a-asset-item id="link1" src="./assets/Panda/meshes/collision/link1.obj"></a-asset-item>
      <a-asset-item id="link2" src="./assets/Panda/meshes/collision/link2.obj"></a-asset-item>
      <a-asset-item id="link3" src="./assets/Panda/meshes/collision/link3.obj"></a-asset-item>
      <a-asset-item id="link4" src="./assets/Panda/meshes/collision/link4.obj"></a-asset-item>
      <a-asset-item id="link5" src="./assets/Panda/meshes/collision/link5.obj"></a-asset-item>
      <a-asset-item id="link6" src="./assets/Panda/meshes/collision/link6.obj"></a-asset-item>
      <a-asset-item id="link7" src="./assets/Panda/meshes/collision/link7.obj"></a-asset-item>

    </assets>
    <a-plane position="0 0 0" rotation="-90 0 0" width="4" height="4" color="#7BC8A4"></a-plane>
    <a-sky color="#ECECEC"></a-sky>
    <a-entity id="robot" position="0 3 0" rotation="-90 0 0" urdf="url: assets/Panda/panda.urdf">

      <a-entity obj-model="obj: #finger"; ></a-entity>
      <a-entity obj-model="obj: #hand" ;></a-entity>
      <a-entity obj-model="obj: #link0" ;></a-entity>
      <a-entity obj-model="obj: #link1" ;></a-entity>
      <a-entity obj-model="obj: #link2" ;></a-entity>
      <a-entity obj-model="obj: #link3" ;></a-entity>
      <a-entity obj-model="obj: #link4" ;></a-entity>
      <a-entity obj-model="obj: #link5" ;></a-entity>
      <a-entity obj-model="obj: #link6" ;></a-entity>
      <a-entity obj-model="obj: #link7" ;></a-entity>

    </a-entity>
    <a-entity id="camera" camera position="0 1.5 0" look-controls wasd-controls></a-entity>
    <a-entity id="rightHand" hand-tracking-grab-controls="hand: right"></a-entity>
    <a-entity id="leftHand" hand-tracking-grab-controls="hand: left"></a-entity>
  </a-scene>
</body>

</html>
```

**Comment by hu-po** [comment]
not quite, I didn't have to add the meshes as `a-asset-item`s. but that is on the right path. I think fundamentally the problem is that whatever computer you are opening the browser on is not finding the path to the meshes (path is wrong, files aren't there, etc).

**Comment by addy1997** [comment]
@hu-po, so the meshes load with the following code but its all messed up

![image](https://github.com/hu-po/aframe-urdf/assets/29406906/b6d3fea7-90bd-43cf-ae57-395125e6b909)
```

 <!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title> URDF A-Frame Example </title>
  <meta name="description" content="URDF • A-Frame">
  <script src="https://aframe.io/releases/1.5.0/aframe.min.js"></script>
  <script src="../dist/aframe-urdf.min.js"></script>
</head>

<body>
  <a-scene background="color: blue" stats
    inspector="url: https://cdn.jsdelivr.net/gh/aframevr/aframe-inspector@master/dist/aframe-inspector.min.js">

    <assets>

    </assets>
    <a-plane position="0 0 0" rotation="-90 0 0" width="4" height="4" color="#7BC8A4"></a-plane>
    <a-sky color="#ECECEC"></a-sky>
    <a-entity id="robot" position="0 3 0" rotation="-90 0 0" urdf="url: assets/Panda/panda.urdf">

      <a-entity obj-model="obj: url(assets/Panda/meshes/collision/finger.obj)" ;></a-entity>
      <a-entity obj-model="obj: url(assets/Panda/meshes/collision/hand.obj)" ;></a-entity>
      <a-entity obj-model="obj: url(assets/Panda/meshes/collision/link0.obj)" ;></a-entity>
      <a-entity obj-model="obj: url(assets/Panda/meshes/collision/link1.obj)" ;></a-entity>
      <a-entity obj-model="obj: url(assets/Panda/meshes/collision/link2.obj)" ;></a-entity>
      <a-entity obj-model="obj: url(assets/Panda/meshes/collision/link3.obj)" ;></a-entity>
      <a-entity obj-model="obj: url(assets/Panda/meshes/collision/link4.obj)" ;></a-entity>
      <a-entity obj-model="obj: url(assets/Panda/meshes/collision/link5.obj)" ;></a-entity>
      <a-entity obj-model="obj: url(assets/Panda/meshes/collision/link6.obj)" ;></a-entity>
      <a-entity obj-model="obj: url(assets/Panda/meshes/collision/link7.obj)" ;></a-entity>

    </a-entity>
    <a-entity id="camera" camera position="0 1.5 0" look-controls wasd-controls></a-entity>
    <a-entity id="rightHand" hand-tracking-grab-controls="hand: right"></a-entity>
    <a-entity id="leftHand" hand-tracking-grab-controls="hand: left"></a-entity>
  </a-scene>
</body>

</html>
```

**Comment by hu-po** [comment]
When you add the obj meshes directly into the html like this:
```
<a-entity obj-model="obj: url(assets/Panda/meshes/collision/link7.obj)" ;></a-entity>
```
they probably lose the relative position information they had inside the urdf. I did not add them to the HTML like this. In my setup the meshes are just referenced inside the urdf via a relative path.
